#!/bin/sh
mkdir -p /var/cache/repos
cd /var/cache/repos
mkdir -p images tumbleweed/repo/oss distribution/leap/42.1/repo/oss update/leap/42.1/oss/ repositories/Cloud:/OpenStack:/Newton/
rsync="rsync -a --delete-after --exclude=".~tmp~" ftp.gwdg.de::opensuse"
#$rsync/tumbleweed/repo/oss/ tumbleweed/repo/oss/
$rsync/distribution/leap/42.1/repo/oss/ distribution/leap/42.1/repo/oss/
$rsync/update/leap/42.1/oss/ update/leap/42.1/oss/
$rsync/repositories/Cloud:/OpenStack:/Newton/ repositories/Cloud:/OpenStack:/Newton/

cd /var/cache/repos/images
for i in openSUSE-Leap-42.1.qcow2 debian.5-0.x86.qcow2 cirros-0.3.4-x86_64-uec.tar.gz
do
    wget -N http://data.zq1.de/images/$i
done

cd /root
git clone https://github.com/SUSE-Cloud/automation.git
cd automation
git checkout clouddemo

