#!/bin/sh
img=/var/cache/repos/images/openSUSE-Leap-42.1.qcow2
if ! [[ -e $img ]] ; then
	echo "missing $img"
	exit 5
fi
rclibvirtd start
rcvirtlogd start
virsh destroy cleanvm
virsh undefine cleanvm
cp -a $img /var/lib/libvirt/images/cleanvm.qcow2
qemu-img create /var/lib/libvirt/images/cleanvm-data.raw 40G
qemu-img create /var/lib/libvirt/images/cleanvm-data2.raw 20G
virsh net-define cleanvm-net.xml
virsh net-start cleanvm
virsh define cleanvm.xml
virsh start cleanvm

. /root/automation/scripts/lib/mkcloud-common.sh
onenode=cleanvm
wait_for 60 1 "netcat -w 2 -z $onenode 22" "node $onenode to be acessible"
ssh-copy-id cleanvm
rsync -a ~/automation/scripts/jenkins/qa_openstack.sh root@cleanvm:
ssh cleanvm "
    zypper mr -d --all
    zypper ar http://192.168.23.1/leap-42.1-oss/ oss
    zypper ar --refresh http://192.168.23.1/leap-42.1-update/ update
"
